### ISSUE TITLE
Unable to configure Parler translations

### ISSUE THREAD

**Issue by vnavascues** [nephila/djangocms-blog#150] opened 2015-09-30 12:11 UTC
Hi,

This is a question. I'm not able to configure entirely these two languages: en, es.
I can **Add post** in both languages. But in **example.com/es/** site, the Blog locale translations are not applied and everything (even category-tag-author words in the slug) is shown in English.

settings.py
```
SITE_ID = 1

LANGUAGES = (
    ## Customize this
    ('en', gettext('en')),
    ('es', gettext('es')),
)

CMS_LANGUAGES = {
    ## Customize this
    1: [
        {
            'public': True,
            'name': gettext('en'),
            'redirect_on_fallback': True,
            'code': 'en',
            'hide_untranslated': False,
        },
        {
            'public': True,
            'name': gettext('es'),
            'redirect_on_fallback': True,
            'code': 'es',
            'hide_untranslated': False,
        },
    ],
    'default': {
        'public': True,
        'redirect_on_fallback': True,
        'hide_untranslated': False,
    },
}

PARLER_LANGUAGES = {
	1: (
		{'code': 'en',},
		{'code': 'es',},
	),
}
```

Did I miss something?

Thanks

**Comment by vnavascues** [comment] 2015-10-01 16:45
I'm working in locale with the **feature/appcnfig** branch code translations work with the same settings.

**Comment by yakky** [comment] 2015-10-01 20:48
@vnavascues does the page the blog is attached to exist in both languages? Does the page data (slug and title) change change when you switch between the two languages? Which django-parler version is installed in the virtualenv?

**Comment by vnavascues** [comment] 2015-10-02 17:03
@yakky here the response:
* Blog is attached to exist in both languages: **yes** (and published).
* Does the page data (slug and title) change when you switch between the two languages: **yes**.
    * I thought **category**, **tags** and **slug** word-paths on the URL were translated too. But is not a problem for me that stay in english.
* Virtualenv significant packages (python 3.4): 
    * django: 1.7.9
    * django-cms: 3.1.3
    * django-parler: 1.5

As I mentioned on Pull requests #147 thread, I don't have this issue with:
* Virtualenv significant packages (python 3.4): 
    * django: 1.7.10
    * django-cms: 3.1.3
    * django-parler: 1.5
    * new djangocms-blog code
    * django-meta-mixin: 0.2.0 dev1

Thanks!

**Comment by yakky** [comment] 2015-10-23 03:02
@vnavascues are you still experiencing issues using latest develop / 0.6.a2?

**Comment by yakky** [comment] 2015-11-01 09:54
@vnavascues closing this as I cannot reproduce. Feel free to reopen in case you have more information about it

**Closed by yakky** 2015-11-01 09:54 UTC
