### ISSUE TITLE
from_db_value() missing 1 required positional argument: 'context'

### ISSUE THREAD

**Issue by atlonxp** [nephila/djangocms-blog#555] opened 2020-05-08 18:35 UTC
Yet another issue that I found and it could relate to `app-data`

![Screen Shot 2020-05-08 at 7 29 41 PM](https://user-images.githubusercontent.com/38250872/81437073-73921f00-9162-11ea-87e5-025c45bd15ab.png)

The issue problem happens while drawing `blog_menu`, which I believe the error occurred in `djangocms_blog/cms_menu.py` line 74 while trying to fetch the data. 

The error caused the function unable to return `context` which cause the error above

![Screen Shot 2020-05-08 at 7 30 18 PM](https://user-images.githubusercontent.com/38250872/81437030-5fe6b880-9162-11ea-95b2-a03ee97e207e.png)

If you have time, could you have a look at this issue. In the meantime, I am also investigating it either. If I found a solution, I will let you know.

**Comment by atlonxp** [comment] 2020-05-13 11:35
@yakky  Have you found any solution for this issue?

**Comment by yakky** [comment] 2020-05-14 20:02
@atlonxp I can't reproduce this
Could you post your pip freeze? `from_db_value` is only used by a handful of dependencies in a djangocms-blog virtualenv (and it's not used by parler, django CMS or djangocms-blog which should be only one involved in the menu), so IDK what triggered your error

**Comment by atlonxp** [comment] 2020-05-14 20:20
Here is the pip freeze (a little bit long, my apology)

Virtual environment: Anaconda

Dependencies:
alabaster==0.7.12
aldryn-apphooks-config==0.5.3
appnope==0.1.0
asgiref==3.2.7
Babel==2.8.0
backcall==0.1.0
certifi==2020.4.5.1
chardet==3.0.4
coverage==4.5.4
cycler==0.10.0
defusedxml==0.6.0
dj-database-url==0.5.0
Django==3.0.6
django-app-helper==2.2.1
django-app-manage==0.9
django-appdata==0.2.2
django-better-test==0.9
django-classy-tags==1.0.0
django-cms==3.7.2
django-filer==1.7.1
django-formtools==2.2
django-js-asset==1.2.2
django-meta==1.6.1
django-mptt==0.11.0
django-parler==2.0.1
django-polymorphic==2.1.2
django-sekizai==1.1.0
django-sortedm2m==3.0.0
django-taggit==1.2.0
django-taggit-autosuggest==0.3.8
django-taggit-templatetags==0.2.5
django-templatetag-sugar==1.0
django-treebeard==4.3.1
djangocms-admin-style==1.5.0
djangocms-apphook-setup==0.4.1
djangocms-attributes-field==1.2.0
djangocms-blog==1.1.0
djangocms-bootstrap4==1.6.0
djangocms-file==2.4.0
djangocms-googlemap==1.4.0
djangocms-icon==1.5.0
djangocms-link==2.6.0
djangocms-picture==2.4.0
djangocms-snippet==2.3.0
djangocms-style==2.3.0
djangocms-text-ckeditor==3.9.0
djangocms-video==2.3.0
docopt==0.6.2
docutils==0.16
easy-thumbnails==2.7
entrypoints==0.3
html5lib==1.0.1
idna==2.9
imagesize==1.2.0
iptools==0.7.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
Jinja2==2.11.2
jupyter==1.0.0
lxml==4.5.0
MarkupSafe==1.1.1
mistune==0.8.4
mock==4.0.2
mpmath==1.1.0
nose==1.3.7
packaging==20.3
pandocfilters==1.4.2
Pillow==5.2.0
prometheus-client==0.7.1
ptyprocess==0.6.0
pyenchant==3.0.1
pyflakes==2.2.0
Pygments==2.6.1
pyparsing==2.4.7
python-coveralls==2.5.0
pytz==2020.1
PyYAML==5.3.1
requests==2.23.0
Send2Trash==1.5.0
sh==1.13.1
six==1.14.0
snowballstemmer==2.0.0
Sphinx==1.8.5
sphinxcontrib-spelling==5.0.0
sphinxcontrib-websupport==1.2.2
sqlparse==0.3.1
Unidecode==1.1.1
unittest-xml-reporting==1.11.0
urllib3==1.25.9
webencodings==0.5.1
widgetsnbextension==3.5.1

**Comment by yakky** [comment] 2020-05-14 21:47
@atlonxp can you try to update to `django-appdata==0.3.0` and `aldryn-apphooks-config==0.6.0`?

**Comment by yakky** [comment] 2020-05-14 21:48
be aware that djangocms-text-ckeditor has some issues with django 3.0 (see https://github.com/divio/djangocms-text-ckeditor/pull/510) so this might be related to that

**Comment by atlonxp** [comment] 2020-05-14 22:54
> @atlonxp can you try to update to django-appdata==0.3.0 and aldryn-apphooks-config==0.6.0?

I have run a clean installation again, with the following instructions:

`
pip install djangocms-blog

pip install aldryn-search djangocms-bootstrap4 djangocms-file djangocms-googlemap djangocms-icon djangocms-link djangocms-picture djangocms-snippet djangocms-style djangocms-text-ckeditor djangocms-video
`

> be aware that djangocms-text-ckeditor has some issues with django 3.0 (see divio/djangocms-text-ckeditor#510) so this might be related to that

As suggested,  I removed `djangocms-text-ckeditor` then

`
./manage.py migrate
./manage.py createsuperuser
`

The AutoSetup still doesn't run autmatically.

![Screen Shot 2020-05-14 at 11 50 33 PM](https://user-images.githubusercontent.com/38250872/81993502-b6aa3180-963d-11ea-961d-cccd716eef10.png)

[requirements.txt](https://github.com/nephila/djangocms-blog/files/4631343/requirements.txt)

**Comment by yakky** [comment] 2020-05-15 00:35
The only way I can reproduce is when creating a blog post or a page from the wizard due to [this djangocms-text-ckeditor error](https://github.com/nephila/djangocms-blog/issues/555#issuecomment-628904311)

You can check your setup against this sample project I uploaded https://github.com/yakky/djangocms-blog-poc

**Comment by yakky** [comment] 2020-05-20 23:19
this has been fixed in djangocms-text-ckeditor 3.9.1

**Closed by yakky** 2020-05-20 23:19 UTC
Labels: status: analysis, type: bug
