### ISSUE TITLE
How Does the Meta Block in Base Template Work?

### ISSUE THREAD

**Issue by tacc-wbomar** [nephila/djangocms-blog#613] opened 2020-06-25 17:19 UTC
## Description

I am confused by purpose of the `meta` block in `base.html` template code.

## Steps to reproduce

1. Confirm working `djangocms-meta` setup:
    1. Have working `djangocms-blog` install.
    2. Have custom `djangocms-blog` _app_ templates, that still has this code in `base.html`:
        ```
        {% block meta %}
            {%  if meta %}
                {% include "meta/meta.html" %}
            {% endif %}
        {% endblock meta %}
        ```
    3. Have working configuration for `djangocms-meta` app. This includes this code in `base.html` _CMS_ template:
         ```
         <head …>
             …
            {% include "meta/meta.html" %}
             …
         </head>
         ```
2. Try to **break** working `djangocms-meta` setup:
    - **Remove** the `{% block meta %}` block of code from `base.html` _app_ template (**not** the _CMS_ template).
3. Try, with _more_ force, to **break** working `djangocms-meta` setup:
    - **Remove** the `{% include "meta…" %}` line of code from `base.html` _CMS_ template (**not** the _app_ template).

## Expected result

1. 💡 The code renders something somewhere.
2. 💡 Removal of the code does **not** render something somewhere.
3. 💡 Removal of the code does **not** render something somewhere.

## Actual result

1. ✓ The code renders `<meta>` tags in the `<head>`.
2. 🤷‍♂️ Removal of the code **seems** to render everything **the same** (as in step 1) everywhere.
3. ✓ Removal of the code does **not** render `<meta>` tags in the `<head>`.

**Comment by yakky** [comment] 2020-07-11 18:21
@tacc-wbomar could you check if the documentation and comment added in #628 helps clarifying the social meta tags behavior and the role of the ``{% block meta %}``?

**Comment by tacc-wbomar** [comment] 2020-08-11 14:53
**Yes.** The `{% block meta %}` is clear, now. Thanks!

(I will try out the "complete social meta tag rendering", like `BLOG_FB` next.)

**Comment by tacc-wbomar** [comment] 2020-08-11 15:22
I cannot find any results in `djangocms-blog` repo (searching via Github), nor (desperation) any results on the Internet (Google search). Are these future (1.2) configuration options?

**Comment by tacc-wbomar** [comment] 2020-08-11 15:22
About `BLOG_FB`, etc.

**Comment by tacc-wbomar** [comment] 2020-08-11 18:41
After experimenting with `{% if meta %}`, I have found that it is not as reliable as expected. *This __may__ be because of my ignorance.* Below is what I learned and my workarounds. Please, tell me whether any of these problems should be a new issue in this repo or another repo.

## Setup

- I have functional CMS.
- I have functional page meta.
- I have functional blog (article) meta.

## Problems

### 1. Page Meta: Making it Work (with Blog Meta?)

#### Problem

Using `{% include "meta/meta.html" %}` does not render page metadata. ([source `djangocms-page-meta`](https://djangocms-page-meta.readthedocs.io/en/latest/configuration.html) → [source `djangocms-meta`](https://django-meta.readthedocs.io/en/latest/models.html#reference-template))

#### Workaround

`…/templates/base.html`
```
{% load … meta page_meta_tags … %}
{% page_meta request.current_page as page_meta %}
<!doctype html>
<html>

<head {% meta_namespaces %}>
  …
  {% block meta %}
    {% include 'djangocms_page_meta/meta.html' with meta=page_meta %}
  {% endblock meta %}
```

I do not remember from where I copied/learned this code.

### 2. Logic: Overwrite Block Even If There Is No `meta`

#### Problem

Using `{% block meta %}   {% if meta %}   …  {% endif meta %}   {% endblock %}` (as documentation offers) will overwrite the block, _even if I have **no** meta_ with which to overwrite the block.

#### Workaround

Using `{% if meta %}   {% block meta %}   …   {% endblock meta %}   {% endif %}`, so that I overwrite the `block` _only **if** I have `meta`_ with which to overwrite the block.

### 3. Data: At Least One `meta` is Available to Template

#### Problem

Using the documentation, and having both page meta and blog meta:
- These values are available on a **blog article** page (in this order):
    1. `'meta': <meta.views.Meta object at 0x7fef6214aeb8>,`\*
    2. `'meta': <module 'meta' from '/usr/local/lib/python3.6/site-packages/meta/__init__.py'>,`\*
- This values is available on **any** page:
    - `'meta': <module 'meta' from '/usr/local/lib/python3.6/site-packages/meta/__init__.py'>,`\*

Thus:
1. __✓__ On a **blog article** page, I get blog meta.
2. __X__ On a **blog article** page, I do __not__ get page meta.
    - Because, the `'meta': <module 'meta' …>` makes `{% if meta %}` evaluate to true.

\* Data retrieved via [`{% debug %}`](https://stackoverflow.com/a/21205925/11817077).

#### Workaround

`…/templates/djangocms_blog/base.html`
```
…
{# A certain code block should be here, but it would cause a bug. #}
{# SEE: `./post_detail.html` #}
{# SEE: https://github.com/nephila/djangocms-blog/issues/613 #}
…
```

`…/templates/djangocms_blog/post_detail.html`
```
…
{# This conditional is irrelevant, because we will always have
   `meta` in this template. This code block belongs in `./base.html`,
   which would benefit from a conditional, but also cause a bug. #}
{# SEE: https://github.com/nephila/djangocms-blog/issues/613 #}
{% if meta %}
  {% block meta %}
    {% include "meta/meta.html" with meta=meta %}
  {% endblock meta %}
{% endif %}
…
```

**Comment by yakky** [comment] 2020-08-19 22:41
@tacc-wbomar this further documentation update should help clarify the proper template layout https://github.com/nephila/djangocms-blog/pull/630

djangocms-page-meta documentation is actually outdated and I will amend that as well

I also included your suggestion at point **2**

Regarding point **3**, blog overrides page meta **on purpose** as you can't have both

**Comment by yakky** [comment] 2020-08-19 22:46
check updated documentation https://djangocms-blog--630.org.readthedocs.build/en/630/features/meta.html

and updated settings documentation https://djangocms-blog--630.org.readthedocs.build/en/630/autodoc/settings.html (which is not updated on RTD due to a build failure)

**Comment by tacc-wbomar** [comment] 2020-08-26 16:34
Thank you.

### Status

- Problem 1 is solved via [option "c"](https://github.com/nephila/djangocms-blog/pull/630/files#diff-719145a46473528a8d06751d04a3943eR53).
- Problem 2 workaround was me inexpertly trying to solve Problem 3. I trust what you decide.
- Problem 3 I explained poorly. I gave data without stating the problem.

### Expected Result
* Metadata is rendered for Home page, Blog page, and any Blog Post.

### Actual Result
* Metadata is rendered for Home page, and any Blog Post.
* Metadata is **not** rendered for Blog page.

### Workaround

#### Remove Surrounding Meta Include Logic from `djangocms_blog/base.html`

```
{% include "meta/meta.html" %}
```

#### Move Meta Include Logic From `djangocms_blog/base.html` to `djangocms_blog/post_detail.html`

```
(…)
    (…)
        {% include "meta/meta.html" %}
    (…)
(…)
```

### Failed Solutions

#### Change Meta Include Logic In `djangocms_blog/base.html`

```
{% block meta %}
    {% if meta %}
        {% include "meta/meta.html" %}
    {% endif %}
{% endblock meta %}
```

```
{% if meta %}
    {% block meta %}
        {% include "meta/meta.html" %}
    {% endblock meta %}
{% endif %}
```

**Comment by tacc-wbomar** [comment] 2020-08-26 18:47
Is my Expected Result strange?

_Perhaps, Blog page should not have page metadata. I really don't understand how users use social media, I'm just trying to get the metadata present on all the pages so I can complete implementation of our blog/news/social-media-metadata feature._

**Comment by yakky** [comment] 2020-08-26 20:43
@tacc-wbomar I don't understand if you can see **any** metadata in the post detail view, or you can see the blog post ones and not the CMS page

If you can't see *any* metadata, that's of course an issue because the it's the whole point of the django-meta integration :)

I will try to replicate the issue in the https://github.com/yakky/djangocms-blog-poc repo

**Comment by tacc-wbomar** [comment] 2020-08-26 21:34
I think this is all the relevant info to show my setup. If helpful, I'll include bits of `settings.py`.

# Variations

## `/base.html` w/ Conditional Indirect Meta Inclusion
`templates/djangocms_blog/base.html`
```
{% if meta %}
    {% block meta %}
        {% include "meta/meta.html" with meta=meta %}
    {% endblock meta %}
{% endif %}
```
_The `templates/djangocms_blog/post_detail.html` has **no** meta inclusion._
- ✅ Home page (has meta)\
  <img width="200" alt="Home page" src="https://user-images.githubusercontent.com/62723358/91357347-b847d180-e7b6-11ea-9143-91b25424c842.png">
- ❌ Blog page (has __no__ meta)\
  <img width="200" alt="Blog page" src="https://user-images.githubusercontent.com/62723358/91357348-b978fe80-e7b6-11ea-864c-36f120273b15.png">
- ✅ Blog post (has meta)\
  <img width="200" alt="Blog post" src="https://user-images.githubusercontent.com/62723358/91357353-baaa2b80-e7b6-11ea-86f5-3e1a876c2aa1.png">

## `/base.html` w/ Unconditional Direct Meta Inclusion
`templates/djangocms_blog/base.html`
```
{% include "meta/meta.html" with meta=meta %}
```
_The `templates/djangocms_blog/post_detail.html` has **no** meta inclusion._
- ✅ Home page (has meta)\
  <img width="200" alt="Home page" src="https://user-images.githubusercontent.com/62723358/91358657-ca2a7400-e7b8-11ea-99e6-d565cae435d6.png">
- ✅ Blog page (has meta)\
  <img width="200" alt="Blog page" src="https://user-images.githubusercontent.com/62723358/91358631-c1d23900-e7b8-11ea-9463-be45171db057.png">
- ❌ Blog post (has __Blog page__ meta)\
  <img width="200" alt="Blog post" src="https://user-images.githubusercontent.com/62723358/91358601-b717a400-e7b8-11ea-9e0f-1faab2223ac5.png">


## `/post_detail.html` w/ Conditional Indirect Meta Inclusion
`templates/djangocms_blog/post_detail.html`
```
{% if meta %}
    {% block meta %}
        {% include "meta/meta.html" with meta=meta %}
    {% endblock meta %}
{% endif %}
```
_The `templates/djangocms_blog/base.html` has **no** meta inclusion._
- ✅ Home page (has meta)\
  <img width="200" alt="Home page" src="https://user-images.githubusercontent.com/62723358/91357347-b847d180-e7b6-11ea-9143-91b25424c842.png">
- ✅ Blog page (has meta)\
  <img width="200" alt="Blog page" src="https://user-images.githubusercontent.com/62723358/91357348-b978fe80-e7b6-11ea-864c-36f120273b15.png">
- ✅ Blog post (has meta)\
  <img width="200" alt="Blog post" src="https://user-images.githubusercontent.com/62723358/91357353-baaa2b80-e7b6-11ea-86f5-3e1a876c2aa1.png">


# Constants

`templates/base.html`
```
{# FAQ: Conditional includes are intentionally verbose #}
{# SEE: https://confluence.tacc.utexas.edu/x/QwI9Cw #}

{% load cms_tags staticfiles sekizai_tags cache i18n %}
<!doctype html>
<html>

{% if settings.FEATURES.blog %}
  {% with path="djangocms_blog_head.html" %}{% include path %}{% endwith %}
{% else %}
<head>
{% endif %}
  …

  <!-- Metadata. -->
  <title>{% block title %} This is my new project home page {% endblock title %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% if settings.FEATURES.blog %}
    {% block meta %}
      {% with path="djangocms_page_meta.html" %}{% include path %}{% endwith %}
    {% endblock meta %}
  {% endif %}
```

`templates/djangocms_blog_head.html`
```
{% load meta %}

<head {% meta_namespaces %}>
```

`templates/djangocms_page_meta.html`
```
{% load page_meta_tags %}
{% page_meta request.current_page as meta %}

{% include 'djangocms_page_meta/meta.html' %}
```

**Comment by yakky** [comment] 2020-08-26 21:38
@tacc-wbomar the settings and a `pip freeze` output would be of great help, thanks!

**Comment by tacc-wbomar** [comment] 2020-08-26 21:49
Okay.

- [`settings.py`](https://gist.github.com/tacc-wbomar/83060efad6dd18af8759fc57f6a108d8)
- [`pip freeze`](https://gist.github.com/tacc-wbomar/9126618582bae3ed4edd40a0458ceadc)

**Comment by tacc-wbomar** [comment] 2020-08-26 21:51
Wait. Bad. The `pip freeze` content is wrong (that's local, not docker).

**Comment by tacc-wbomar** [comment] 2020-08-26 21:52
Okay `pip freeze` content is accurate, now.

**Comment by yakky** [comment] 2020-08-26 22:04
thanks for the details
I confirm I have been able to reproduce the issue

Can you try replacing in `/templates/djangocms_blog/base.html`

```html+django
{% block meta %}
    {% comment %}
    This is needed if you can't add ``{% include "meta/meta.html" %}`` in the django CMS template attached to the blog
    page.
    If you have something like the snippet below in the main template used by the django CMS page, you don't need
    this block and you can safely remove it when customizing the blog templates

    ...
    <html>
        <head>
        <title>{% block title %}{% page_attribute 'title' %}{% endblock title %}</title>
        {% include "meta/meta.html" %}
        ...

    {% endcomment %}
    {% if meta %}
        {% include "meta/meta.html" %}
    {% endif %}
{% endblock meta %}
```
with

```html+django
{% block meta %}
    {% if meta %}
        {% include "meta/meta.html" %}
    {% else %}
        {{ block.super }}
    {% endif %}
{% endblock meta %}
```

**Comment by tacc-wbomar** [comment] 2020-08-26 22:06
Yes! That works.

**Comment by yakky** [comment] 2020-08-26 22:09
awesome!

i updated #630 to fix the base template

Thanks a lot for your patience and your super detailed reports!

**Comment by yakky** [comment] 2020-08-26 22:16
@tacc-wbomar thanks again. Closing this via merge of #630

**Closed** 2020-08-26 22:16 UTC
Labels: status: approved, type: bug, type: documentation
