### ISSUE TITLE
Category plugin doesn't work with multiple blogs

### ISSUE THREAD

**Issue by kynsi** [nephila/djangocms-blog#414] opened 2018-01-17 18:02 UTC
I you have two blog-instances on one site the category-plugin links all the categories to the first blog-instance even if you've selected another blog-instance.

**Comment by yakky** [comment] 2018-01-17 18:15
What are the Django, django CMS, djangocms-blog versions?

**Comment by kynsi** [comment] 2018-01-17 18:40
Django 1.10.8, django CMS 3.4.5, djangocms-blog 0.9b10

**Comment by yakky** [comment] 2018-01-17 22:11
I can't reproduce this
![screenshot_20180117_230944](https://user-images.githubusercontent.com/714711/35069796-932017e2-fbdb-11e7-9a22-ebfae848b323.png)

**Comment by kynsi** [comment] 2018-01-17 22:48
What does the url of blog2 in the plugin look like? Beneath Categories?
In my case the **blog2** category plugin url is like this "/blog1/category/cat1" instead of "/blog2/category/cat1"

**Comment by yakky** [comment] 2018-01-17 22:52
Sorry, I misunderstood your report.
The URL is `/blog2/category/cat-1-blog-2/`
Can you test rc1?

**Comment by kynsi** [comment] 2018-01-17 23:16
Just tried but keeps crashing:
"AttributeError: attribute menu_structure not found"
This after using fresh install with django 1.11 and then downgrading to 1.10.8.

**Comment by yakky** [comment] 2018-01-17 23:36
Maybe some other packages have been upgraded which broke the existing virtualenv

Have you upgraded using '-U' option?

**Comment by kynsi** [comment] 2018-01-17 23:38
Deleted the database and now works with django 1.10.8. 1.11 doesn't work.
And the plugin works as it should. I have to check why it doesn't work on my other site tomorrow.

**Comment by yakky** [comment] 2018-01-17 23:40
Correct. Django 1.11 is not supported yet (because some of our dependencies does not support it. From internal tests we will be able to support 1.11 as soon as dependencies will )

**Comment by kynsi** [comment] 2018-01-17 23:41
Thanks!

**Comment by yakky** [comment] 2018-01-18 21:22
Thanks for your feedback
Closing this

**Closed by yakky** 2018-01-18 21:22 UTC
Labels: bug

**Comment by kynsi** [comment] 2018-01-20 13:27
Turned out my templates still had the old url definitions..
