### ISSUE TITLE
InconsistentMigrationHistory - blog can not be appended to the existing project

### ISSUE THREAD

**Issue by pawelmarkowski** [nephila/djangocms-blog#349] opened 2017-03-06 09:05 UTC
Migration cmsplugin_filer_image.0004_auto_20160120_0950 is applied before its dependency djangocms_blog.0020_thumbnail_move4

Is this requirement necessary?

**Comment by yakky** [comment] 2017-03-06 10:21
@pawelmarkowski which djangocms-blog / cmsplugin filer versions are you using?

**Comment by yakky** [comment] 2017-03-06 10:35
@pawelmarkowski how about cmsplugin-filer?

**Comment by pawelmarkowski** [comment] 2017-03-06 10:39
cmsplugin_filer_file.__version__
'1.1.3' 

everything latest as I wrote before

**Comment by yakky** [comment] 2017-03-06 10:49
So you previously had cmsplugin-filer and filer, updated both to newest versions and then you added djangocms-blog to 0.8.10, right? Asking just to be able to reproduce your case.

**Comment by pawelmarkowski** [comment] 2017-03-06 10:58
yes.

A blog migration file (mentioned at the beggining) has a rule: execute
migration before specified filer migration.

06.03.2017 11:49 "Iacopo Spalletti" <notifications@github.com> napisał(a):

**Comment by yakky** [comment] 2017-03-06 11:12
@pawelmarkowski yes. it was setup due to the migration of ThumbnailOption from cmsplugin-filer to filer. I'm going to check soon how to fix this issue. Thanks for reporting

**Comment by pawelmarkowski** [comment] 2017-03-06 11:26
@yakky thanks a lot, it is very important for me. I would say that it is blocker

**Comment by yakky** [comment] 2017-03-06 21:16
@pawelmarkowski could you check linked PR? I just dropped ``run_before``. It's not ready for merge but it should allow you to proceed

**Comment by pawelmarkowski** [comment] 2017-03-07 11:07
Migration cmsplugin_filer_image.0004_auto_20160120_0950 is applied before its dependency djangocms_blog.0019_thumbnail_move3
Migration cmsplugin_filer_image.0004_auto_20160120_0950 is applied before its dependency djangocms_blog.0017_thumbnail_move on database 'default'.
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration cmsplugin_filer_image.0004_auto_20160120_0950 is applied before its dependency djangocms_blog.0018_thumbnail_move2 on database 'default'.

I removed run_before section and it works properly. So you can do that too and it should be ok.

**Comment by yakky** [comment] 2017-03-11 23:19
Fixed in 0.8.12

**Closed by yakky** 2017-03-11 23:19 UTC
