### ISSUE TITLE
"Change Post" screen is half-empty

### ISSUE THREAD

**Issue by bbirand** [nephila/djangocms-blog#408] opened 2018-01-05 22:58 UTC
We built a blog using `djangocms-blog` and tested it extensively on our local environment. We've just deployed it to a staging environment and the "Edit Post" screen is somehow empty:

![image](https://user-images.githubusercontent.com/334435/34632166-f64244f6-f241-11e7-88d8-176133a55310.png)

There are no failed requests or Javascript errors. We loaded the exact same data via a fixture, so the data should be exact same as well.

As a comparison point, this is what it looks like on our local dev:

![image](https://user-images.githubusercontent.com/334435/34632068-67f37a3a-f241-11e7-8a44-cf43271951be.png)

Any idea why this is happening? We have absolutely no clue where to look.

Thanks

**Comment by yakky** [comment] 2018-01-06 12:56
@bbirand This is an error when rendering the form due to some missing data on the development environment. Does apphook config exists on the testing environment?

**Comment by bbirand** [comment] 2018-01-08 22:17
Thank you, @yakky  for the quick reply!

I'm checking the blog page's "Advanced Settings" screen. And I do see the config:
![image](https://user-images.githubusercontent.com/334435/34695144-bf51f57e-f497-11e7-94d9-eb6335757d61.png)

Is there something I am missing? If this is not the right place to look, please do tell me how I can debug.

Thanks!

**Comment by yakky** [comment] 2018-01-08 22:48
@bbirand it looks correct
Does the "add post" form looks the same?

**Comment by yakky** [comment] 2018-01-08 22:52
could you provide the output of `pip freeze`?

**Comment by bbirand** [comment] 2018-01-08 22:56
yes, "add post" looks similar:
![image](https://user-images.githubusercontent.com/334435/34696406-af9333d2-f49c-11e7-8580-09c5332bce60.png)

I'll try the `pip freeze` command shortly

**Comment by yakky** [comment] 2018-01-08 23:07
I wonder why the `Application instance name` is shown in this screenshot https://github.com/nephila/djangocms-blog/issues/408#issuecomment-356114586
It should be hidden: any js error in the browser console when opening the page advanced settings form?

**Comment by yakky** [comment] 2018-01-24 07:56
@bbirand could you check if #424 fixes your issue?

**Comment by yakky** [comment] 2018-02-21 22:42
@bbirand The only way I have reproduced is on Django 1.11 which is still not supported. Support coming in #430 (but really only dependencies needed changes)

**Comment by yakky** [comment] 2018-03-12 07:04
@bbirand can you test aldryn-apphooks-config 0.4.0rc1? That should fix this problem

**Comment by protoroto** [comment] 2023-08-04 08:18
@yakky I think we can safely close this. @bbirand what do you think?

**Closed** 2023-08-07 06:27 UTC
Labels: type: bug, status: feedback needed
