### ISSUE TITLE
duplicate slug crashes post

### ISSUE THREAD

**Issue by kynsi** [nephila/djangocms-blog#415] opened 2018-01-17 18:04 UTC
If you add a post with an already existing slug it crashes the creation of that post, and you can't delete it. It also crashes all article-listings.
It would be nice to check if the slug exists before creating it.

**Comment by yakky** [comment] 2018-01-17 18:15
What are the Django, django CMS, djangocms-blog versions?

**Comment by kynsi** [comment] 2018-01-17 18:40
Djanbgo 1.10.8, django CMS 3.4.5, djangocms-blog 0.9b10

**Comment by yakky** [comment] 2018-01-17 22:16
Saving a post with and existing slug should return this error message on error save

![screenshot_20180117_231350](https://user-images.githubusercontent.com/714711/35069973-192cd690-fbdc-11e7-8012-0a889332b2b4.png)

I tested this in 0.9rc1, although no change since b10 should have impacted this area

**Comment by kynsi** [comment] 2018-01-17 22:52
I'm getting the following error:

"IntegrityError at /cms_wizard/create/

(1062, "Duplicate entry 'nl-test-slug' for key 'djangocms_blog_post_translation_language_code_39d00571_uniq'")
"

Could it be because I'm using a different language?

**Comment by yakky** [comment] 2018-01-17 22:53
Ah, the wizard it's a different thing. I will check there!

**Comment by yakky** [comment] 2018-01-17 22:57
@kynsi confirmed when using the wizard

**Comment by yakky** [comment] 2018-01-18 21:15
@kynsi linked PR should fix the issue
You can test this with:
```
pip uninstall djangocms-blog && pip install https://github.com/nephila/djangocms-blog/archive/hotfix/slug_clean.zip
```

**Comment by kynsi** [comment] 2018-01-20 13:25
Fixed! Turned out my templates didn't use the new url defiunitions.

**Comment by yakky** [comment] 2018-01-20 18:44
@kynsi I merged the PR
You can test develop (and rc2 later ) to see if the issue is now fixed

**Closed** 2018-01-20 18:43 UTC
Labels: type: bug
